"use client";

/**
 * 100M-row scale proof (docs/ENGINEERING-PLAN.md §E1).
 *
 * `billing_events`: 100,000,000 synthetic rows in 8 hive-partitioned
 * quarterly parquet files (ZSTD, 1M-row row groups, ~510 MB total),
 * generated by
 * scripts/generate-scale-data.sh and served from GitHub Pages
 * (CORS `*` + HTTP Range). DuckDB-WASM registers the files as one view and
 * range-reads only parquet footers + the row groups each query touches, so
 * the browser fetches megabytes, not the half-gigabyte dataset.
 *
 * Honesty rules: the row count shown comes from a real `count(*)` at
 * registration; the "MB fetched" figures come from byte-level accounting of
 * the worker's actual XHRs (net-stats BroadcastChannel), with the page's
 * resource-timing delta as fallback. When neither source reports bytes we
 * show wall-time only — never a guessed number.
 */

import { useCallback, useState } from "react";
import { toast } from "sonner";
import { subscribeNetStats } from "@kontier-ri/datasource";
import { dataSource } from "@/lib/datasource";
import {
  migrateDoc,
  useDashboardStore,
  type DashboardDoc,
} from "@/lib/dashboard-store";

export const SCALE_DATASET = "scale_events";
export const SCALE_DATA_HOST = "https://theemperor66.github.io";
const SCALE_DATA_BASE = `${SCALE_DATA_HOST}/kontier-scale-data/events`;
/** Total dataset size on the host (see kontier-scale-data/manifest.json). */
export const SCALE_TOTAL_MB = 511;

/** The dataset is fixed: quarter=2024-Q1 … quarter=2025-Q4 (8 partitions). */
export function scaleDataQuarters(): string[] {
  return Array.from({ length: 8 }, (_, i) => {
    const year = 2024 + Math.floor(i / 4);
    return `${year}-Q${(i % 4) + 1}`;
  });
}

export function scaleDataUrls(): string[] {
  return scaleDataQuarters().map(
    (q) => `${SCALE_DATA_BASE}/quarter=${q}/part-0.parquet`,
  );
}

/**
 * The "Scale proof" page: 3 live tiles against the remote view. Raw SQL so
 * the queries stay column-frugal (aggregates CAST to DOUBLE — DuckDB-WASM
 * HUGEINT sums do not survive the Arrow → JS bridge for charts). The
 * `quarter = '2025-Q4'` predicates hive-prune 7 of the 8 files; the
 * events-per-day scan touches every file but only the tiny sorted
 * `event_ts` column.
 */
function buildScaleDoc(mode: "dark" | "light", rowCount: number): DashboardDoc {
  const rows = rowCount.toLocaleString("en-US");
  return migrateDoc({
    title: "100M-row scale proof",
    theme: { mode },
    filters: { filters: [], dateRange: null },
    pages: [
      {
        id: "scale_page",
        name: "Scale proof",
        tiles: [
          {
            id: "scale_tile_events",
            type: "chart",
            title: `Events per day — all ${rows} rows, live over HTTP`,
            layout: { x: 0, y: 0, w: 12, h: 5 },
            spec: {
              dataset: SCALE_DATASET,
              query: {
                sql: `SELECT strftime(event_ts, '%Y-%m-%d') AS day, CAST(count(*) AS DOUBLE) AS events FROM ${SCALE_DATASET} GROUP BY 1 ORDER BY 1`,
              },
              chartType: "line",
              xKey: "day",
              format: { value: "compact" },
            },
            annotations: [],
          },
          {
            id: "scale_tile_revenue",
            type: "chart",
            title: "Revenue by country — last 3 months (€M)",
            layout: { x: 0, y: 5, w: 7, h: 5 },
            spec: {
              dataset: SCALE_DATASET,
              query: {
                sql: `SELECT country, CAST(sum(amount_cents) / 100.0 / 1000000.0 AS DOUBLE) AS revenue_eur_m FROM ${SCALE_DATASET} WHERE status = 'succeeded' AND quarter = '2025-Q4' GROUP BY 1 ORDER BY 2 DESC`,
              },
              chartType: "bar",
              xKey: "country",
            },
            annotations: [],
          },
          {
            id: "scale_tile_failrate",
            type: "chart",
            title: "Failed-payment rate by gateway — last 3 months",
            layout: { x: 7, y: 5, w: 5, h: 5 },
            spec: {
              dataset: SCALE_DATASET,
              query: {
                sql: `SELECT gateway, CAST(sum(CASE WHEN status = 'failed' THEN 1 ELSE 0 END) AS DOUBLE) / CAST(count(*) AS DOUBLE) AS failed_rate FROM ${SCALE_DATASET} WHERE quarter = '2025-Q4' GROUP BY 1 ORDER BY 2 DESC`,
              },
              chartType: "bar",
              xKey: "gateway",
              color: "var(--destructive)",
              format: { value: "percent" },
            },
            annotations: [],
          },
        ],
      },
    ],
  });
}

/** Bytes already attributed to the scale host on the page's own timeline. */
function resourceTimingBytes(): number {
  if (typeof performance === "undefined") return 0;
  return performance
    .getEntriesByType("resource")
    .filter((e) => e.name.startsWith(SCALE_DATA_HOST))
    .reduce((sum, e) => {
      const r = e as PerformanceResourceTiming;
      return sum + (r.transferSize || r.encodedBodySize || 0);
    }, 0);
}

function formatMB(bytes: number): string {
  return `${(bytes / 1e6).toFixed(1)} MB`;
}

const TOAST_ID = "scale-demo";

async function runScaleDemo(
  mode: "dark" | "light",
  resetDashboard: (doc: DashboardDoc) => void,
): Promise<void> {
  let workerBytes = 0;
  const stopNetStats = subscribeNetStats((m) => {
    if (m.url.startsWith(SCALE_DATA_HOST)) workerBytes += m.bytes;
  });
  const timingBase = resourceTimingBytes();
  const fetchedBytes = (): number =>
    Math.max(workerBytes, resourceTimingBytes() - timingBase);
  const t0 = performance.now();
  const chip = (): void => {
    const secs = ((performance.now() - t0) / 1000).toFixed(1);
    const bytes = fetchedBytes();
    toast.loading(
      `Counting 100,000,000 remote rows… ${secs}s${bytes > 0 ? ` · ${formatMB(bytes)} fetched` : ""}`,
      { id: TOAST_ID },
    );
  };
  chip();
  const ticker = setInterval(chip, 300);

  try {
    const meta = await dataSource.registerRemoteParquet(
      SCALE_DATASET,
      scaleDataUrls(),
      {
        group: "remote",
        description: `8 hive-partitioned parquet files (~${SCALE_TOTAL_MB} MB) on GitHub Pages, read via HTTP Range`,
      },
    );
    clearInterval(ticker);
    const wall = ((performance.now() - t0) / 1000).toFixed(1);
    const bytes = fetchedBytes();
    // Cross-origin dev servers cannot see Accept-Ranges on the data host
    // (not CORS-exposed), so DuckDB falls back to whole-file reads there.
    // On the deployed site (same origin as the data) it range-reads only
    // parquet metadata here. Keep the copy honest in both modes.
    const fetchedNote =
      bytes > 0 && bytes < SCALE_TOTAL_MB * 1e6 * 0.1
        ? ` — ${formatMB(bytes)} fetched of the ${SCALE_TOTAL_MB} MB dataset (parquet metadata only)`
        : bytes > 0
          ? ` — ${formatMB(bytes)} moved (this origin reads files whole; the deployed site range-reads only what a query needs)`
          : "";
    toast.success(
      `${SCALE_DATASET} registered: ${meta.rowCount.toLocaleString("en-US")} rows counted in ${wall}s${fetchedNote}.`,
      { id: TOAST_ID, duration: 10_000 },
    );
    resetDashboard(buildScaleDoc(mode, meta.rowCount));

    // Once the tiles' queries stop moving bytes, report the honest total.
    let last = -1;
    let stable = 0;
    let elapsed = 0;
    const settle = setInterval(() => {
      elapsed += 1;
      const now = fetchedBytes();
      stable = now === last ? stable + 1 : 0;
      last = now;
      if ((stable >= 4 && now > 0) || elapsed >= 60) {
        clearInterval(settle);
        stopNetStats();
        if (now > 0) {
          toast.info(
            now < SCALE_TOTAL_MB * 1e6 * 0.5
              ? `Live tiles drew from ${formatMB(now)} of the ${SCALE_TOTAL_MB} MB dataset — DuckDB-WASM range-read only the row groups it needed.`
              : `Live tiles moved ${formatMB(now)} — this origin falls back to whole-file HTTP reads (cross-origin hides Range support). The deployed site range-reads only the row groups it needs.`,
            { duration: 12_000 },
          );
        }
      }
    }, 1000);
  } catch (err) {
    clearInterval(ticker);
    stopNetStats();
    toast.error(
      `Could not load the remote dataset: ${err instanceof Error ? err.message : String(err)}`,
      { id: TOAST_ID },
    );
  }
}

/** Empty-state hook behind the "Load 100M-row live demo" button. */
export function useScaleDemo(): { load: () => void; loading: boolean } {
  const [loading, setLoading] = useState(false);
  const mode = useDashboardStore((s) => s.doc.theme.mode);
  const resetDashboard = useDashboardStore((s) => s.resetDashboard);

  const load = useCallback(() => {
    if (loading) return;
    setLoading(true);
    void runScaleDemo(mode, resetDashboard).finally(() => setLoading(false));
  }, [loading, mode, resetDashboard]);

  return { load, loading };
}
